### ISSUE TITLE
Bank doesn't auto close when outside usage range

### ISSUE THREAD

**Issue by radhaz** [checkem/SUCC-bag#1]
If I don't manually close the bank bag and "walk away" from the banker the bag remains open on my screen. Items cannot be manipulated but it doesn't go away until I manually close it.

**Comment by checkem** [comment]
Fixed in https://github.com/checkem/SUCC-bag/commit/6b18bd582dfa84c4305ad1ea4be50bd268d5f97c

Thanks for contribution.
