### ISSUE TITLE
No Sort Button

### ISSUE THREAD

**Issue by Lemonadez** [checkem/SUCC-bag#18]
![image](https://user-images.githubusercontent.com/19479119/151896859-ffd2c7b7-0e40-4673-ae58-ef7cce4db6c8.png)

**Comment by Anatei** [comment]
Need use only Clean_Up version, specified in Readme.md

**Comment by checkem** [comment]
This version has pretty much been abandoned. Use one of the forks.
Sorry for the late reply.
