### ISSUE TITLE
[Feature Request] Title frame needs to extend over the bank breakout panel

### ISSUE THREAD

**Issue by radhaz** [checkem/SUCC-bag#5]
Currently with the "breakout panel" in the bank that happens after you open the bank and then a bag just kind of floats to the right visually "unbalanced" by extending the title frame across the breakout panel it would help give it some visual balance.

**Comment by checkem** [comment]
Added in https://github.com/checkem/SUCC-bag/commit/fdc9d5e1b12b37ddc65ff53c6676e42cac893db1
![azxcvgfds](https://cloud.githubusercontent.com/assets/17740865/23336139/94e4c566-fb7b-11e6-93ea-8e68d23dfaa0.jpg)

**Comment by radhaz** [comment]
I like the fix! as far as aesthetics go it's much more balanced! I have to ask though, did you intentionally attach the users inventory/bag frame to the bank when it opens or was that an unintentional side effect? I can get used to it, but think it's not as convenient as leaving the inventory bags wherever the user wants them.

**Comment by checkem** [comment]
Yes that was intentional. many things like positioning, color, textures e.t.c. I will reconsider as soon as I get to user settings. There is no way to predict what will be more convenient or visually appealing for each individual user, so I will make the settings adjustable to preference.
