### ISSUE TITLE
Intermittent Conflict with either Aux addon or Enh Tooltip

### ISSUE THREAD

**Issue by radhaz** [checkem/SUCC-bag#7]
So using this addon in conjunction with other addons (I suspect Aux or Enh Tooltip) I noted that the tooltip frame no longer goes all the way around the information. http://imgur.com/a/Otd9U would be an example of what I'm talking about.

**Comment by checkem** [comment]
What version of aux/enhtooltip are you using? I do not have this behaviour neither with aux nor auctioneer/enh tooltip and enchantrix both embedded and detached,
![untitled1231](https://cloud.githubusercontent.com/assets/17740865/23335422/47348f2e-fb6a-11e6-83e7-90f8bd3b1212.png)

**Comment by radhaz** [comment]
When I wrote this I could have swore I was using enh tooltip but it turns out I'm using "tinytip, tinytipextras, tinytipoptions" I apologize for not properly vetting the conflict before reporting fwiw though:

Tinytip looks like  v1.4.4
Aux is version is not listed in the file anywhere that I can find (readme.md, *.toc), etc) but it was downloaded from their github 12feb and installed same day.

My "install" started as a base install of the frostadamus pack https://github.com/Frostadamus/Frost-UI-stuff that I've tried to update/keep current as well as add a few other useful addons (questie, vguide, archud2 come to mind)

**Comment by radhaz** [comment]
I updated the title of this issue to reflect the behavior of the fault in that it's intermittent. Without rhyme or reason the conflict will sometimes be present upon login and sometimes not, if the fault is present the only way I've found to rectify it is to fully restart the game (/reload & logout do not work).

**Comment by checkem** [comment]
I can't seem to reproduce the bug. In other hand, SUCC-bag has little to do with game tooltips.

**Comment by radhaz** [comment]
I am unable to consistently reproduce the bug and given the infrequency of it recommend closing this issue until I can.
